# Generated by Django 5.0.4 on 2024-05-04 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('message', models.CharField(max_length=150)),
                ('viewed', models.BooleanField(default=False)),
                ('types', models.CharField(choices=[('amount_transfer', 'amount_transfer'), ('amount_transfer_request', 'amount_transfer_request'), ('amount_transfer_result', 'amount_transfer_result')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notif', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound Sterling')], max_length=5)),
                ('target_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound Sterling')], max_length=5)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('pay_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_from_user', to=settings.AUTH_USER_MODEL)),
                ('pay_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('obtainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obtain_user', to=settings.AUTH_USER_MODEL)),
                ('transferrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
